# Generated by Django 4.1.9 on 2024-01-12 17:03

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentsdetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('DOB', models.DateField()),
                ('Mobilenumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('Emailid', models.EmailField(max_length=255)),
                ('Addressline1', models.CharField(max_length=255)),
                ('Addressline2', models.CharField(max_length=255)),
                ('District', models.CharField(max_length=255)),
                ('Postal_pincode', models.BigIntegerField()),
                ('mark_1', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('mark_2', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('mark_3', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('mark_4', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('mark_5', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('Total', models.IntegerField()),
                ('Average', models.DecimalField(decimal_places=2, max_digits=3)),
                ('Registernumber', models.CharField(max_length=255)),
            ],
        ),
    ]
