# Generated by Django 4.1.9 on 2024-01-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsdetails',
            name='Average',
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
    ]
